name : This is a github action
on: [push]
jobs: 
      test:
       runs-on: ubuntu-latest
       steps:
         - name: test
           run: echo test

      build:
        runs-on: ubuntu-latest
        steps:
         - name: build
           run: sleep 2m && echo build

      deploy:
         runs-on: ubuntu-latest
         steps:
         - name: deploy
           run: echo deploy
